## Write a program to extract the items from a list by using index numbers

In [1]:
l = [11,22,33,42,1,133,10]

# I want items of 0,1,3,5,6 index 

index = [0,1,3,5,6]
n = []

for i in index:
    n.append(l[i])
    
print(n)

[11, 22, 42, 133, 10]


In [5]:
l[0]

11

In [6]:
l[0,1]     # we can't get more than 1 item by using indexing in list, but by using array we can get more than 1 items 

TypeError: list indices must be integers or slices, not tuple

In [10]:
l[[0,1]]

TypeError: list indices must be integers or slices, not list

In [2]:
# By using Numpy 
# If we want to access the multiple items at a time by using indexing then we have to pass the list of that multiple indexes for indexing
# Syntax :- a[list of indexes]

# Ex. a[[0,1,3,5,6]], array[[-1,-3,-6]],...

# we can't write it as a[0,1,3,5,6], we have to pass the list of indexes only not multiple index numbers directly

In [3]:
import numpy as np

a = np.array(l)  # Coverting list to numpy array

print(a[index])
a[0]

[ 11  22  42 133  10]


11

In [4]:
a[[0,1,3,5,6]]

array([ 11,  22,  42, 133,  10])

In [7]:
a[0]

11

In [8]:
a[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [9]:
a[[0,1]]

array([11, 22])

In [12]:
x=12,34,54
x

(12, 34, 54)

In [13]:
x,y=12


TypeError: cannot unpack non-iterable int object

In [16]:
x,y=1,2
print(x,y)

1 2


In [17]:
x,y=1,2,3

ValueError: too many values to unpack (expected 2)